version: '2'

services:
  mysql:
    image: mysql:5
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: limesurvey

  limesurvey:
    links:
      - mysql

    environment:
      - "DISABLE_MYSQL=yes"

    ports:
      - "80:80"
    volumes:
      - upload:/app/upload
    image:
      crramirez/limesurvey:latest

volumes:
  mysql:
  upload:
